# Generated by Django 6.0.1 on 2026-02-03 22:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_base',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='imagem_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='referencias/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('KIT', 'kit festa'), ('BOLO', 'bolo'), ('DOCES', 'doces'), ('SALGADOS', 'salgados'), ('CUPCAKE', 'cupcake'), ('CASEIRINHO', 'caseirinho')], default='KIT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='ecommerce.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.variacaoproduto'),
        ),
    ]
