# Generated by Django 6.0.1 on 2026-02-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_produto_categoria_remove_produto_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('recheio_bolo', 'Recheio de Bolo'), ('recheio_cupcake', 'Recheio do Mini Cupcake'), ('recheio_caseirinho', 'Recheio do Caseirinho'), ('massa_bolo', 'Massa do Bolo'), ('massa_caseirinho', 'Massa do Caseirinho'), ('massa_cupcake', 'Massa do Mini Cupcake'), ('doce', 'Doces'), ('salgado', 'Salgados')], max_length=50)),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='sabores',
            field=models.ManyToManyField(blank=True, related_name='variacoes', to='ecommerce.sabor'),
        ),
    ]
