# Generated by Django 6.0.1 on 2026-02-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_sabor_variacaoproduto_sabores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacaoproduto',
            name='sabores',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='massa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_massa', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='recheio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recheio', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
