# Generated by Django 6.0.1 on 2026-02-05 18:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_variacaoproduto_sabores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='criando_em',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='qtd_doces',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='qtd_salgados',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='massa',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'massa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_massa', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='recheio',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'recheio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recheio', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ecommerce.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ItemPedidoDoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doces_escolhidos', to='ecommerce.itempedido')),
                ('sabor', models.ForeignKey(limit_choices_to={'tipo': 'doce'}, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.sabor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoSalgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salgados_escolhidos', to='ecommerce.itempedido')),
                ('sabor', models.ForeignKey(limit_choices_to={'tipo': 'salgado'}, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.sabor')),
            ],
        ),
    ]
