# Generated by Django 6.0.1 on 2026-02-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_valor_total_pedido_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='max_opcoes_doces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='max_opcoes_salgados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='massa',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__startswith': 'massa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_massa', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='recheio',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__startswith': 'recheio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recheio', to='ecommerce.sabor'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='qtd_doces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='qtd_salgados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
